import { proxy, useSnapshot } from "valtio";
import { RevalidateCache } from "../common/navigation-helpers";
import { PERSONA_ATTRIBUTE, PersonaModel } from "./persona-services/models";
import {
  CreatePersona,
  UpsertPersona,
} from "./persona-services/persona-service";
import { generateStarterPrompts } from "./persona-services/starter-prompts-service";

class PersonaState {
  private defaultModel: PersonaModel = {
    id: "",
    name: "",
    description: "",
    personaMessage: "",
    startMessage: "",
    starterPrompts: undefined,
    createdAt: new Date(),
    isPublished: false,
    type: "PERSONA",
    userId: "",
  };

  public isOpened: boolean = false;
  public errors: string[] = [];
  public persona: PersonaModel = { ...this.defaultModel };

  public updateOpened(value: boolean) {
    this.isOpened = value;
  }

  public updatePersona(persona: PersonaModel) {
    this.persona = {
      ...persona,
    };
    this.isOpened = true;
  }

  public newPersona() {
    this.persona = {
      ...this.defaultModel,
    };
    this.isOpened = true;
  }

  public newPersonaAndOpen(persona: {
    name: string;
    description: string;
    personaMessage: string;
    startMessage: string;
  }) {
    // Generate starter prompts for this persona
    let starterPrompts: string[] | undefined = undefined;
    if (persona.personaMessage && persona.personaMessage.trim() !== "") {
      try {
        starterPrompts = generateStarterPrompts(persona.personaMessage, persona.name);
      } catch (error) {
        console.warn("[PersonaStore] Failed to generate starter prompts in newPersonaAndOpen:", error);
      }
    }
    
    this.persona = {
      ...this.defaultModel,
      name: persona.name,
      description: persona.description,
      personaMessage: persona.personaMessage,
      startMessage: persona.startMessage,
      starterPrompts: starterPrompts,
    };
    this.isOpened = true;
  }

  public updateErrors(errors: string[]) {
    this.errors = errors;
  }
}

export const personaStore = proxy(new PersonaState());

export const usePersonaState = () => {
  return useSnapshot(personaStore);
};

export const addOrUpdatePersona = async (previous: any, formData: FormData) => {
  personaStore.updateErrors([]);

  const model = FormDataToPersonaModel(formData);
  const response =
    model.id && model.id !== ""
      ? await UpsertPersona(model)
      : await CreatePersona(model);

  if (response.status === "OK") {
    personaStore.updateOpened(false);
    RevalidateCache({
      page: "persona",
    });
  } else {
    personaStore.updateErrors(response.errors.map((e) => e.message));
  }
  return response;
};

export const FormDataToPersonaModel = (formData: FormData): PersonaModel => {
  const name = formData.get("name") as string;
  const personaMessage = formData.get("personaMessage") as string;
  
  // Check for manual starter prompts first
  const manualPrompt1 = (formData.get("starterPrompt1") as string)?.trim();
  const manualPrompt2 = (formData.get("starterPrompt2") as string)?.trim();
  const manualPrompt3 = (formData.get("starterPrompt3") as string)?.trim();
  
  let starterPrompts: string[] | undefined = undefined;
  
  // Use manual prompts if any are provided
  if (manualPrompt1 || manualPrompt2 || manualPrompt3) {
    starterPrompts = [];
    if (manualPrompt1) starterPrompts.push(manualPrompt1);
    if (manualPrompt2) starterPrompts.push(manualPrompt2);
    if (manualPrompt3) starterPrompts.push(manualPrompt3);
    
    // Ensure we have exactly 3 prompts by auto-generating missing ones
    if (starterPrompts.length < 3 && personaMessage && personaMessage.trim() !== "") {
      try {
        const autoGenerated = generateStarterPrompts(personaMessage, name);
        while (starterPrompts.length < 3 && autoGenerated.length > 0) {
          const nextPrompt = autoGenerated[starterPrompts.length];
          if (nextPrompt && !starterPrompts.includes(nextPrompt)) {
            starterPrompts.push(nextPrompt);
          } else {
            break;
          }
        }
      } catch (error) {
        console.warn("[PersonaStore] Failed to auto-generate missing starter prompts:", error);
      }
    }
    
    console.log(`[PersonaStore] Using manual starter prompts for ${name}:`, starterPrompts);
  } else if (personaMessage && personaMessage.trim() !== "") {
    // Auto-generate all prompts if none are manually provided
    try {
      starterPrompts = generateStarterPrompts(personaMessage, name);
      console.log(`[PersonaStore] Auto-generated starter prompts for ${name}:`, starterPrompts);
    } catch (error) {
      console.warn("[PersonaStore] Failed to generate starter prompts:", error);
    }
  }
  
  return {
    id: formData.get("id") as string,
    name: name,
    description: formData.get("description") as string,
    personaMessage: personaMessage,
    startMessage: (formData.get("startMessage") as string) || "",
    starterPrompts: starterPrompts,
    isPublished: formData.get("isPublished") === "on" ? true : false,
    userId: "", // the user id is set on the server once the user is authenticated
    createdAt: new Date(),
    type: PERSONA_ATTRIBUTE,
  };
};
